name: Docker Image CI for GHCR

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        run: ./ci/extract-version.sh

      - name: Login to GHCR
        env:
          GHCR_USERNAME: KirilsTurkins
          GHCR_TOKEN: ${{ secrets.GH_TOKEN }}
        run: ./ci/ghcr-login.sh

      - name: Build and push
        env:
          IMAGE_NAME: ghcr.io/solution-wcmd/email-microservice
        run: ./ci/build-and-push.sh